;源文件地址：https://github.com/bulianglin/demo/blob/main/nodnsleak.ini

[custom]
;自定义规则：
;@WIKI——直连
ruleset=DIRECT,[]DOMAIN-SUFFIX,atwiki.jp
;adobe系软件防止正版弹窗——阻止
ruleset=REJECT,[]DOMAIN-KEYWORD,adobe
;lanzou蓝奏云——直连
ruleset=DIRECT,[]GEOSITE,lanzou
;deepseek——直连
ruleset=DIRECT,[]GEOSITE,deepseek
;cloudflare规则列表内的workers域名——代理
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,workers.dev
;cloudflare——直连
ruleset=DIRECT,[]GEOSITE,cloudflare
;steam下载——直连
ruleset=DIRECT,[]GEOSITE,steam@cn
ruleset=DIRECT,[]DOMAIN,steamcdn-a.akamaihd.net
ruleset=DIRECT,[]DOMAIN-SUFFIX,cm.steampowered.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,steamserver.net
;微软规则列表内需代理的网站——代理
ruleset=🚀 节点选择,[]GEOSITE,github
ruleset=🚀 节点选择,[]GEOSITE,onedrive
;微软——直连
ruleset=DIRECT,[]GEOSITE,microsoft
;原规则：
;解决DNS泄露，无分流群组
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]DIRECT`.*

enable_rule_generator=true
overwrite_original_rules=true
